/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "server_funcs.h"

bool_t
xdr_mult_array (XDR *xdrs, mult_array *objp)
{
	register int32_t *buf;

	 if (!xdr_double (xdrs, &objp->num))
		 return FALSE;
	 if (!xdr_array (xdrs, (char **)&objp->arr.arr_val, (u_int *) &objp->arr.arr_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_int_array (XDR *xdrs, int_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->arr.arr_val, (u_int *) &objp->arr.arr_len, ~0,
		sizeof (int), (xdrproc_t) xdr_int))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_double_array (XDR *xdrs, double_array *objp)
{
	register int32_t *buf;

	 if (!xdr_array (xdrs, (char **)&objp->arr.arr_val, (u_int *) &objp->arr.arr_len, ~0,
		sizeof (double), (xdrproc_t) xdr_double))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_intpair (XDR *xdrs, intpair *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->num1))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->num2))
		 return FALSE;
	return TRUE;
}
