/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SERVER_FUNCS_H_RPCGEN
#define _SERVER_FUNCS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct mult_array {
	double num;
	struct {
		u_int arr_len;
		int *arr_val;
	} arr;
};
typedef struct mult_array mult_array;

struct int_array {
	struct {
		u_int arr_len;
		int *arr_val;
	} arr;
};
typedef struct int_array int_array;

struct double_array {
	struct {
		u_int arr_len;
		double *arr_val;
	} arr;
};
typedef struct double_array double_array;

struct intpair {
	int num1;
	int num2;
};
typedef struct intpair intpair;

#define SERVER_PROG 0x23451111
#define AVG_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AVG 1
extern  double * avg_1(int_array *, CLIENT *);
extern  double * avg_1_svc(int_array *, struct svc_req *);
#define Max_min 2
extern  intpair * max_min_1(int_array *, CLIENT *);
extern  intpair * max_min_1_svc(int_array *, struct svc_req *);
#define MULT 3
extern  double_array * mult_1(mult_array *, CLIENT *);
extern  double_array * mult_1_svc(mult_array *, struct svc_req *);
extern int server_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AVG 1
extern  double * avg_1();
extern  double * avg_1_svc();
#define Max_min 2
extern  intpair * max_min_1();
extern  intpair * max_min_1_svc();
#define MULT 3
extern  double_array * mult_1();
extern  double_array * mult_1_svc();
extern int server_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_mult_array (XDR *, mult_array*);
extern  bool_t xdr_int_array (XDR *, int_array*);
extern  bool_t xdr_double_array (XDR *, double_array*);
extern  bool_t xdr_intpair (XDR *, intpair*);

#else /* K&R C */
extern bool_t xdr_mult_array ();
extern bool_t xdr_int_array ();
extern bool_t xdr_double_array ();
extern bool_t xdr_intpair ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SERVER_FUNCS_H_RPCGEN */
